- community.docker.docker_compose_v2:
    project_name: grafana
    definition:
      services:
          grafana:
            image: grafana/grafana-enterprise
            environment:
              GF_SERVER_ROOT_URL: https://hackupc.co/grafana
              GF_SERVER_SERVE_FROM_SUBPATH: "true"
            ports:
              - 8080:3000
            volumes:
              - data:/var/lib/grafana
            extra_hosts: 
              - "host.docker.internal:host-gateway"
      volumes:
        data:
  register: output

- ansible.builtin.debug:
    var: output
